<a href="https://colab.research.google.com/github/shubhsk321go/Data-science/blob/main/NumPy_indexing_and_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Q -->  WHAT IS INDEXING

# Ans --> Indexing refers to selecting the specific element or part of the array in numpy
# numpy uses the 0 based indexing in python
# numpy uses the negative indexing in numpy
# if the index will be  not found the index error will be raised and pop up

arr= ([10,20,30,40,50,60])

print(arr)
print(arr[0])

print(arr[1])
print(arr[2])
print(arr[3])
print(arr[-1])
print(arr[-2])

[10, 20, 30, 40, 50, 60]
10
20
30
40
60
50


In [3]:
# slicing of array

# it includes the getting multiple elements from the array
# syntax ---> array[start:stop:step]
# start--> it will be the starting index in the array from which the slicing will be performed  It is also included.
# end --> it will be the ending index in the array to which the array will be ended. It will be excluded.
# step -->


arr = np.array([10,12,32,25,20,19,22,35])
print(arr)
print(arr[0:]) #strating from the first elemant and end is not defined so it will be going till last element
print(arr[:4]) #starting is not defined so it will be started from the begining and will go to the index n-1 which is 4-1 =index number 3 (25)
print(arr[::2]) #start and end is not specified in the slicing and the step of 2 is present so it will start from the begining and will stop at end but will extract one element and leave one and so on


[10 12 32 25 20 19 22 35]
[10 12 32 25 20 19 22 35]
[10 12 32 25]
[10 32 20 22]


In [4]:
# reverse of the array

print(arr[::-1]) #we will use the negative number as the step and the result will show us the reverse array

[35 22 19 20 25 32 12 10]


In [5]:
# fancy slicing in numpy

print(arr)

print(arr[[0,2,4]])



[10 12 32 25 20 19 22 35]
[10 32 20]


In [6]:
# Filtering
# booloean masking
# conditions --> 1. TRUE   2. FALSE


print(arr[arr>20])

[32 25 22 35]


In [7]:
# Reshaping and manupulating of array

# Reshaping means the changing the dimensions of the array
# it changes the shape of the array however the size (number of elements) in the array will remain same.
print(arr) #1d array
# .reshape(shape of array)
print(arr.reshape(2,4)) #2d array
print(arr.reshape(4,2)) #2d array of different size
print(arr.reshape(1,8)) #2d array of 1 row
print(arr.reshape(2,2,2)) #3d array
arr2= np.array(arr.reshape(2,2,2))
print(arr2)


[10 12 32 25 20 19 22 35]
[[10 12 32 25]
 [20 19 22 35]]
[[10 12]
 [32 25]
 [20 19]
 [22 35]]
[[10 12 32 25 20 19 22 35]]
[[[10 12]
  [32 25]]

 [[20 19]
  [22 35]]]
[[[10 12]
  [32 25]]

 [[20 19]
  [22 35]]]


In [8]:
# changing the multidimentional array into 1d array

# there are 2 methods in this
# .ravel()
# .flatten()
# changing the multidimentional array into 1d array

# there are 2 methods in this
# .ravel() --> view original will be changed and will be affected
# .flatten() --> copy the array and so that the original array does not affected

print(arr2.ravel())
print(arr2.flatten())

[10 12 32 25 20 19 22 35]
[10 12 32 25 20 19 22 35]
