<a href="https://colab.research.google.com/github/shubhsk321go/Data-science/blob/main/Practice_for_data_analyst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We are starting the numpy here for practice


In [2]:
import numpy as np

Arravali = np.array(np.random.randint(10,45,(8,2)))

print(f"The defined array is \n{Arravali}")
print(f"\n The shape of the array is {Arravali.shape}")

The defined array is 
[[16 11]
 [28 16]
 [38 36]
 [30 22]
 [38 44]
 [16 27]
 [18 14]
 [35 37]]

 The shape of the array is (8, 2)


In [ ]:
nilgiri = np.transpose(Arravali)
print(nilgiri)
print(nilgiri.shape)

[[35 24 16 43 43 30 38 22]
 [22 13 18 13 20 10 10 37]]
(2, 8)


In [ ]:
Random_Array= np.array(np.random.randint(10,50,(3,4,5)))
print(Random_Array)
print(Random_Array.shape)
print(Random_Array.ndim)

[[[12 24 20 32 15]
  [25 26 17 43 31]
  [36 20 36 36 37]
  [24 13 36 26 10]]

 [[47 34 19 14 14]
  [27 18 18 42 14]
  [27 37 24 29 22]
  [39 36 39 47 13]]

 [[34 42 19 28 47]
  [12 24 13 34 11]
  [43 39 44 28 23]
  [29 24 34 39 13]]]
(3, 4, 5)
3


In [ ]:
transposed= np.transpose(Random_Array)
print(transposed)
print(transposed.shape)
print(transposed.ndim)

[[[12 47 34]
  [25 27 12]
  [36 27 43]
  [24 39 29]]

 [[24 34 42]
  [26 18 24]
  [20 37 39]
  [13 36 24]]

 [[20 19 19]
  [17 18 13]
  [36 24 44]
  [36 39 34]]

 [[32 14 28]
  [43 42 34]
  [36 29 28]
  [26 47 39]]

 [[15 14 47]
  [31 14 11]
  [37 22 23]
  [10 13 13]]]
(5, 4, 3)
3


In [ ]:
#Reshape

Reshape= np.reshape(Random_Array,(5,12))
print(Reshape)
print(Reshape.shape)
print(Reshape.ndim)

[[12 24 20 32 15 25 26 17 43 31 36 20]
 [36 36 37 24 13 36 26 10 47 34 19 14]
 [14 27 18 18 42 14 27 37 24 29 22 39]
 [36 39 47 13 34 42 19 28 47 12 24 13]
 [34 11 43 39 44 28 23 29 24 34 39 13]]
(5, 12)
2


In [ ]:
#resize

Resized= np.resize(Random_Array,(4,62))
print(Resized)
print(Resized.shape)
print(Resized.ndim)


[[12 24 20 32 15 25 26 17 43 31 36 20 36 36 37 24 13 36 26 10 47 34 19 14
  14 27 18 18 42 14 27 37 24 29 22 39 36 39 47 13 34 42 19 28 47 12 24 13
  34 11 43 39 44 28 23 29 24 34 39 13 12 24]
 [20 32 15 25 26 17 43 31 36 20 36 36 37 24 13 36 26 10 47 34 19 14 14 27
  18 18 42 14 27 37 24 29 22 39 36 39 47 13 34 42 19 28 47 12 24 13 34 11
  43 39 44 28 23 29 24 34 39 13 12 24 20 32]
 [15 25 26 17 43 31 36 20 36 36 37 24 13 36 26 10 47 34 19 14 14 27 18 18
  42 14 27 37 24 29 22 39 36 39 47 13 34 42 19 28 47 12 24 13 34 11 43 39
  44 28 23 29 24 34 39 13 12 24 20 32 15 25]
 [26 17 43 31 36 20 36 36 37 24 13 36 26 10 47 34 19 14 14 27 18 18 42 14
  27 37 24 29 22 39 36 39 47 13 34 42 19 28 47 12 24 13 34 11 43 39 44 28
  23 29 24 34 39 13 12 24 20 32 15 25 26 17]]
(4, 62)
2


In [ ]:
#flattened

Flattened= np.ravel(Random_Array)
print(Flattened)
print(Flattened.shape)
print(Flattened.ndim)

[12 24 20 32 15 25 26 17 43 31 36 20 36 36 37 24 13 36 26 10 47 34 19 14
 14 27 18 18 42 14 27 37 24 29 22 39 36 39 47 13 34 42 19 28 47 12 24 13
 34 11 43 39 44 28 23 29 24 34 39 13]
(60,)
1


In [ ]:
# flatten

flattened = Random_Array.flatten()
print(flattened)
print(flattened.shape)
print(flattened.ndim)
#

[12 24 20 32 15 25 26 17 43 31 36 20 36 36 37 24 13 36 26 10 47 34 19 14
 14 27 18 18 42 14 27 37 24 29 22 39 36 39 47 13 34 42 19 28 47 12 24 13
 34 11 43 39 44 28 23 29 24 34 39 13]
(60,)
1


In [ ]:
#inserting in Numpy

a= np.random.randint(10,50,(3,4,5))
print(a)
print(a.shape)

[[[48 30 36 27 46]
  [43 28 42 38 18]
  [15 37 24 23 40]
  [33 22 22 11 47]]

 [[19 22 31 10 34]
  [40 41 41 48 33]
  [24 20 47 36 21]
  [31 24 41 13 16]]

 [[35 29 15 27 46]
  [31 17 35 48 28]
  [34 19 46 43 23]
  [14 40 46 49 45]]]
(3, 4, 5)


In [ ]:
# Insert command

np.insert(a,3,100,axis=2)

array([[[ 48,  30,  36, 100,  27,  46],
        [ 43,  28,  42, 100,  38,  18],
        [ 15,  37,  24, 100,  23,  40],
        [ 33,  22,  22, 100,  11,  47]],

       [[ 19,  22,  31, 100,  10,  34],
        [ 40,  41,  41, 100,  48,  33],
        [ 24,  20,  47, 100,  36,  21],
        [ 31,  24,  41, 100,  13,  16]],

       [[ 35,  29,  15, 100,  27,  46],
        [ 31,  17,  35, 100,  48,  28],
        [ 34,  19,  46, 100,  43,  23],
        [ 14,  40,  46, 100,  49,  45]]])

In [ ]:
# Insert command

np.insert(a,3,100,axis=0)

array([[[ 48,  30,  36,  27,  46],
        [ 43,  28,  42,  38,  18],
        [ 15,  37,  24,  23,  40],
        [ 33,  22,  22,  11,  47]],

       [[ 19,  22,  31,  10,  34],
        [ 40,  41,  41,  48,  33],
        [ 24,  20,  47,  36,  21],
        [ 31,  24,  41,  13,  16]],

       [[ 35,  29,  15,  27,  46],
        [ 31,  17,  35,  48,  28],
        [ 34,  19,  46,  43,  23],
        [ 14,  40,  46,  49,  45]],

       [[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]]])

In [ ]:
# Insert command

np.insert(a,3,100,axis=1)

array([[[ 48,  30,  36,  27,  46],
        [ 43,  28,  42,  38,  18],
        [ 15,  37,  24,  23,  40],
        [100, 100, 100, 100, 100],
        [ 33,  22,  22,  11,  47]],

       [[ 19,  22,  31,  10,  34],
        [ 40,  41,  41,  48,  33],
        [ 24,  20,  47,  36,  21],
        [100, 100, 100, 100, 100],
        [ 31,  24,  41,  13,  16]],

       [[ 35,  29,  15,  27,  46],
        [ 31,  17,  35,  48,  28],
        [ 34,  19,  46,  43,  23],
        [100, 100, 100, 100, 100],
        [ 14,  40,  46,  49,  45]]])

In [ ]:
# append command

a= np.random.randint(10,80,(3,4,5))
print(a)
print(a.shape)

[[[49 71 41 39 32]
  [70 70 62 66 12]
  [54 66 50 39 23]
  [70 58 22 35 37]]

 [[78 32 72 45 47]
  [57 36 39 14 79]
  [44 21 42 70 42]
  [38 16 59 78 21]]

 [[60 24 70 19 14]
  [76 40 54 56 78]
  [31 22 63 48 75]
  [31 70 21 44 50]]]
(3, 4, 5)


In [ ]:
# np.append(a,100)

In [ ]:
b= np.random.randint(10,80,(3,4,5))
print(b)
print(b.shape)

[[[63 13 76 25 40]
  [79 44 31 77 43]
  [23 28 49 15 10]
  [45 43 54 21 69]]

 [[76 11 29 18 31]
  [17 72 54 37 26]
  [33 24 18 42 50]
  [66 18 26 12 71]]

 [[45 78 30 65 21]
  [35 79 28 77 73]
  [79 63 16 74 34]
  [16 37 67 34 26]]]
(3, 4, 5)


In [ ]:
np.append(a,b,axis = 1)
#

array([[[49, 71, 41, 39, 32],
        [70, 70, 62, 66, 12],
        [54, 66, 50, 39, 23],
        [70, 58, 22, 35, 37],
        [63, 13, 76, 25, 40],
        [79, 44, 31, 77, 43],
        [23, 28, 49, 15, 10],
        [45, 43, 54, 21, 69]],

       [[78, 32, 72, 45, 47],
        [57, 36, 39, 14, 79],
        [44, 21, 42, 70, 42],
        [38, 16, 59, 78, 21],
        [76, 11, 29, 18, 31],
        [17, 72, 54, 37, 26],
        [33, 24, 18, 42, 50],
        [66, 18, 26, 12, 71]],

       [[60, 24, 70, 19, 14],
        [76, 40, 54, 56, 78],
        [31, 22, 63, 48, 75],
        [31, 70, 21, 44, 50],
        [45, 78, 30, 65, 21],
        [35, 79, 28, 77, 73],
        [79, 63, 16, 74, 34],
        [16, 37, 67, 34, 26]]])

In [ ]:
 # np.delete statement in NumPy
np.delete(a,3,axis=1)


array([[[49, 71, 41, 39, 32],
        [70, 70, 62, 66, 12],
        [54, 66, 50, 39, 23]],

       [[78, 32, 72, 45, 47],
        [57, 36, 39, 14, 79],
        [44, 21, 42, 70, 42]],

       [[60, 24, 70, 19, 14],
        [76, 40, 54, 56, 78],
        [31, 22, 63, 48, 75]]])

In [ ]:
#np.unique statement in numpy


In [ ]:
# zeros

np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
# ones

np.ones([3,2,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
# full

np.full((3,4,5),100)

array([[[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]]])

In [ ]:
# use to make the sequences of series
# a-range
# arange
np.arange(2,30,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [3]:
# creating identity matrices

identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
